name:                perudo-server
version:             0.1.0.0
github:              "githubuser/row-swagger"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

dependencies:
- base >= 4.7 && < 5
- row-types-extra
- servant-swagger-ui
- servant-server
- servant-swagger
- hasql
- hasql-th
- uuid
- row-types
- aeson
- text
- swagger2
- QuickCheck
- generic-random
- constraints
- bytestring
- warp
- lens
- generic-lens
- record-hasfield
- record-dot-preprocessor
- template-haskell

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -j


executables:
  server-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -j
    dependencies: []
    # - perudo-server
