name:                row-types-extra
version:             0.1.0.0
github:              "githubuser/row-swagger"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

dependencies:
- base >= 4.7 && < 5
- row-types
- aeson
- text
- swagger2
- servant-swagger
- QuickCheck
- generic-random
- constraints
- bytestring
- servant-swagger-ui
- servant-server
- warp
- lens
- generic-lens
- record-hasfield
- record-dot-preprocessor
- template-haskell

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -j
