resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/5.yaml

packages:
- .

extra-deps:
- git: https://github.com/Sorokin-Anton/row-types.git
  commit: 6167ae4e0ce0633c08fcf5b7cde1d148dd058ece

